services:
  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile.rate
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: 'redis:alpine3.20'
    ports:
      - '6379:6379'
  ab:
    build:
      context: .
      dockerfile: Dockerfile.ab
  grafana-k6:
    image: grafana/k6
    volumes:
      - ./testes:/testes
    command: run /testes/teste.js
    depends_on:
      - rate-limiter
    