FROM golang:1.22.3-alpine3.20 AS BUILDER
WORKDIR /app
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o rate-limiter cmd/main.go

FROM alpine:3.20.0
WORKDIR /app
COPY --from=BUILDER /app/rate-limiter /app/rate-limiter
COPY ./.env /app/.env
RUN apk add --no-cache ca-certificates
ENTRYPOINT ["./rate-limiter"]